server:
  application:
    name: custom_florist
  port: 8080
spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/swd392_custom_florist}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:123456}
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  security:
      oauth2:
        client:
          registration:
            google:
              client-id: ${GOOGLE_CLIENT_ID:833352017043-3bd6ieqdukrkggbb7vo3acb8mmqh6oua.apps.googleusercontent.com}
              client-secret: ${GOOGLE_CLIENT_SECRET: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}
              scope: profile, email
              redirect-uri: "http://localhost:4200/auth/google/callback"
          provider:
            google:
              authorization-uri: https://accounts.google.com/o/oauth2/auth
              token-uri: https://oauth2.googleapis.com/token
              user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
              user-name-attribute: email
api:
  prefix: /custom-florist
jwt:
  expiration: 2592000 #30 days = 30 * 24 * 60 * 60
  expiration-refresh-token: 5184000 #60 days = 60 * 24 * 60 * 60
  secretKey: ${JWT_SECRET_KEY:U3t9aQv9tqdw/mwvxDrl4ebJKiurzORBmS1gzYKDeT+zJOTg0xAauB7HpLCYasbo}
open:
  api:
    title: Custom Florist API
    version: 1.0.0
    description: Meta API service
    serverUrl: http://localhost:8080
    serverName: server test
payment:
  vnpay:
    url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    returnUrl: http://localhost:8080/custom-florist/api/v1/payment/vn-pay-callback
    tmnCode: 07IVPW62
    secretKey: ${VNPAY_SECRET_KEY:6LGP36DS9S6IYW5R523GNZRK9E6X7216}
    version: 2.1.0
    command: pay
    orderType: Flower


